# Generated by Django 6.0.1 on 2026-01-22 20:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TENANT_OWNER", "Gérant (Propriétaire)"),
                            ("COMPTABLE", "Comptable"),
                            ("COLLABORATEUR", "Collaborateur"),
                            ("ADMIN_CABINET", "Admin Cabinet"),
                        ],
                        default="COLLABORATEUR",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="companies.entreprise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "db_table": "users_membership",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_membe_user_id_a489e4_idx"
                    ),
                    models.Index(
                        fields=["entreprise"], name="users_membe_entrepr_6d2bb4_idx"
                    ),
                    models.Index(fields=["role"], name="users_membe_role_7a3cbb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "entreprise"),
                        name="unique_user_entreprise_membership",
                    )
                ],
            },
        ),
    ]
