# Generated by Django 6.0.1 on 2026-01-19 05:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='companies.entreprise')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'db_table': 'treasury_banktransaction',
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='treasury.banktransaction')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='companies.entreprise')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Reconciliation',
                'verbose_name_plural': 'Reconciliations',
                'db_table': 'treasury_reconciliation',
            },
        ),
    ]
