# Generated by Django 6.0.1 on 2026-01-19 05:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("siret", models.CharField(max_length=14, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "db_table": "companies_entreprise",
                "indexes": [
                    models.Index(fields=["name"], name="companies_e_name_a0d986_idx"),
                    models.Index(
                        fields=["is_active"], name="companies_e_is_acti_656f26_idx"
                    ),
                ],
            },
        ),
    ]
