# Generated by Django 6.0.1 on 2026-01-19 05:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('vat_number', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.entreprise')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'invoices_customer',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ISSUED', 'Émise'), ('PAID', 'Payée'), ('CANCELED', 'Annulée')], default='DRAFT', max_length=16)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hash_prev', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_curr', models.CharField(blank=True, max_length=64, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.customer')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.entreprise')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_path', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_documents', to='companies.entreprise')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Document',
                'verbose_name_plural': 'Invoice Documents',
                'db_table': 'invoices_invoicedocument',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='companies.entreprise')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'invoices_invoiceline',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['entreprise', 'name'], name='invoices_cu_entrepr_9c6860_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entreprise', 'issue_date'], name='invoices_in_entrepr_c94793_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entreprise', 'status'], name='invoices_in_entrepr_bf0422_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('entreprise', 'number'), name='uniq_invoice_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['entreprise', 'invoice'], name='invoices_in_entrepr_fab068_idx'),
        ),
    ]
